data_path: "../../datasets/MVTEC"
distillType: st # rd,ead, st
backbone: resnet18 # any cnn model for, any resnet or wide resnet for rd, medium or small for ead
out_indice: [2,3] # for st
obj: wood
phase: test
save_path: "./results"
TrainingData:
  epochs: 50
  batch_size: 8
  lr: 0.0004
  img_size: 224
  crop_size: 224
