data_path: "/home/christianjaspert/masterthesis/DistillationAD/datasets/MVTEC"
distillType: dbfad #st #st #dbfad # rd,ead, st
backbone: resnet18 # any cnn model for, any resnet or wide resnet for rd, medium or small for ead
out_indice: [2,3] # for st

myworklabel: "Attention1"
myworkswitch: False

#obj: myfabric_hm_anomalie
obj: myfabric_dataset #w625 h337 not cropped test: w2500 h1350#
#obj: carpet #carpet
#obj: fabric2cropped_png #w1250 h675
debugparams: False
phase: train
save_path: "./results"
save_path_modified_architecture: "./results_modified_architecture"
hm_sorting: True
blendfactor: 0.4
cropping: True #False: uses the cropped tiny pictures in the test phase, True: uses the big pictures and crops them
croppingfactor: 4
overlapfactor: 0.404
threshold: 0.0001
TrainingData:
  epochs: 50 #100
  batch_size: 4 #4
  lr: 0.0005 #0.0005
  img_size_h: 256 #337 #224 #337 #1350
  img_size_w: 256 # #625 #2500
  crop_size: 256 #337
  norm: True # normalize features before loss calculation
TestData:
  img_size_h: 256
  img_size_w: 256
  crop_size: 256
